<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository

{
  public function getAdverts ($page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
     //Jointure sur l'attribut image
      ->leftJoin('a.image', 'i')
      ->addSelect('i')
     // Jointure sur l'attribut categories
      ->leftJoin('a.categories', 'c')
      ->addSelect('c')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;
    
    
    $query
     //On définit l'annonce à partir de laquelle commencer la liste
     ->setFirstResult(($page-1)*$nbPerPage)
     // Ainsi que le nombre d'annonce à afficher sur une page
     ->setMaxResults($nbPerPage)
     ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    return new Paginator($query, true);
  }
  
    public function getPublishedQueryBuilder()
    {
      return $this
        ->createQueryBuilder('a')
        ->where('a.published = :published')
        ->setParameter('published', true)
      ;
    }
}
